### ISSUE TITLE
SyntaxError: invalid syntax when installed

### ISSUE THREAD

**Issue by 43121** [numericube/lektor-i18n-plugin#18]
Hi,
I have some troubles when installing the plugin. Here is the traceback :

```
Traceback (most recent call last):
  File "/usr/local/bin/lektor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lektor/lib/python3.6/site-packages/lektor/cli.py", line 627, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lektor/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lektor/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lektor/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lektor/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lektor/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lektor/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lektor/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lektor/lib/python3.6/site-packages/lektor/cli.py", line 552, in plugins_list_cmd
    ctx.load_plugins()
  File "/usr/local/lektor/lib/python3.6/site-packages/lektor/cli.py", line 131, in load_plugins
    initialize_plugins(self.get_env())
  File "/usr/local/lektor/lib/python3.6/site-packages/lektor/pluginsystem.py", line 122, in initialize_plugins
    plugins = load_plugins()
  File "/usr/local/lektor/lib/python3.6/site-packages/lektor/pluginsystem.py", line 116, in load_plugins
    rv[ep.name] = ep.load()
  File "/usr/local/lektor/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lektor/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/unknow/.cache/lektor/packages/26e29e198c383c73b8acd273c755cdc0/lektor_i18n.py", line 285
    except IOError, e:
                  ^
SyntaxError: invalid syntax
```

Thank you

**Comment by odeckmyn** [comment]
This plugin is only for Python 2 so far.
