### ISSUE TITLE
RuntimeError: No executable specified

### ISSUE THREAD

**Issue by sgrinschpun** [numericube/lektor-i18n-plugin#2]
On first build after adding the config file, specifying the translatable fields and defining locales in the project file I get this error.

I'm on Lektor 2.3 and OSX.

Started build
i18n activated, with main language en
Parsing templates for i18n into ../../../../../var/folders/73/ntmw03rd5zsfy201qv1b7rww0000gn/T/templates.pot
Finished build in 0.00 sec
Traceback (most recent call last):
  File "/usr/local/bin/lektor", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 187, in build_cmd
    success = _build()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 180, in _build
    failures = builder.build_all()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1104, in build_all
    self.env.plugin_controller.emit('before-build-all', builder=self)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/pluginsystem.py", line 161, in emit
    rv[plugin.id] = handler(**kwargs)
  File "/Users/sgrinchspun/Library/Caches/Lektor/packages/4edec7f33e13d2d9811e1610c75619b0/lektor_i18n.py", line 298, in on_before_build_all
    translations.parse_templates(templates_pot_filename)
  File "/Users/sgrinchspun/Library/Caches/Lektor/packages/4edec7f33e13d2d9811e1610c75619b0/lektor_i18n.py", line 88, in parse_templates
    portable_popen(cmdline).wait()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/utils.py", line 482, in portable_popen
    raise RuntimeError('No executable specified')
RuntimeError: No executable specified

**Comment by odeckmyn** [comment]
is GNU gettext correctly installed ?

**Comment by evilangel-ru** [comment]
Hi, have the same problem. macOS 10.15.4. lektor 3.1.3, plugin 0.2
gettext correctly installed from brew. 
```
brew info gettext
gettext: stable 0.20.2 (bottled)
GNU internationalization (i18n) and localization (l10n) library
https://www.gnu.org/software/gettext/
/usr/local/Cellar/gettext/0.20.2_1 (1,923 files, 18.6MB) *
  Poured from bottle on 2020-05-02 at 01:22:04
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gettext.rb
```

Any ideas how to fix it

**Comment by jcharaoui** [comment]
This should be fixed in 0.5.0, if not please reopen this issue.
